from .base import Base, session, xenforo_engine, XenforoSession, Session
from .associations import user_group_association
from .user import User
from .npc import NpcList
from .item import ItemList
from .item_value_override import ItemValueOverride
from .plugin_manifest import PluginManifestSection
from .pb_loadout import PersonalBestLoadout
from .component_layout import GroupComponentLayout
from .player_state import (
    PlayerState,
    PlayerCollectionLogItem,
    PlayerCombatAchievementVarps,
    PlayerQuestState,
    PlayerDiaryTier,
)
from .player import Player, IgnoredPlayer
from .group import Group
from .user_configuration import UserConfiguration
from .group_patreon import GroupPatreon
from .drop import Drop
from .drop_moderation import (
    DropGroupModeration,
    COUNTING_STATUSES,
    EXCLUDING_STATUSES,
    UNDOABLE_STATUSES,
)
from .collection import CollectionLogEntry
from .combat_achievement import CombatAchievementEntry
from .personal_best import PersonalBestEntry
from .player_pet import PlayerPet
from .quest_completion import QuestCompletionEntry
from .player_death import PlayerDeath
from .diary_completion import DiaryCompletionEntry
from .group_configuration import GroupConfiguration
from .group_notification import GroupNotification
from .group_notification_blacklist import GroupNotificationBlacklist
from .group_notification_always_list import GroupNotificationAlwaysList
from .notified_submission import NotifiedSubmission
from .notification_queue import NotificationQueue
from .player_npc_kc import PlayerNpcKc
from .player_notification_prefs import PlayerNotificationPrefs
from .embed import GroupEmbed, Field
from .site import GroupSite, GroupSitePage
from .guild_meta import Guild, GroupWomAssociation, GroupPersonalBestMessage, LBUpdate
from .webhooks import Webhook, BackupWebhook, WebhookPendingDeletion, NewWebhook
from .lootboard import LootboardStyle
from .analytics import (
    PlayerItemHourlyTotals,
    PlayerNpcHourlyTotals,
    NpcEhbRate,
    GroupRecentDrops,
    PlayerDailyAggregates,
    PlayerLootData,
    PlayerExperience,
    HistoricalMetrics,
    Log,
)
from datetime import datetime
from .premium_features import ( 
    PremiumFeature, 
    FeatureActivation,
    PointCredit, 
    PointDebit, 
    RecurringPointGrant)
from .tickets import Ticket, TicketMessage
from .group_points import PlayerPoints, GroupPointConfig, GroupPointMods, GroupPointTimedEvent, GroupPointBlacklist, GroupPointSeason
from .video_upload import VideoUpload
from .seasonal_drop import SeasonalDrop
from .seasonal_personal_best import SeasonalPersonalBestEntry
from .seasonal_collection_log import SeasonalCollectionLogEntry
from .seasonal_combat_achievement import SeasonalCombatAchievementEntry
from .seasonal_pet import SeasonalPlayerPet
from .seasonal_quest_completion import SeasonalQuestCompletionEntry
from .drop_split import DropSplit
from .web import GroupAdmin, GroupEventManager, Announcement, AuditLog, DiscordOutbox, DocsPage, SiteRedirect, Suggestion, SuggestionMessage
from .dev_tracker import DevProject, DevTask, DevSubtask, DevNote, PROJECT_STATUSES, TASK_STATUSES
from .file_transfer import (
    FileTransfer,
    FileTransferVersion,
    TRANSFER_MAX_BYTES,
    TRANSFER_RETENTION_DAYS,
    TRANSFER_UPLOADER_ROLES,
)
from .surface_read import SurfaceRead
from .group_notice import GroupNotice
from .chat import (
    ChatThread,
    ChatParticipant,
    ChatMessage,
    ChatRead,
    CHAT_THREAD_KINDS,
    CHAT_THREAD_STATUSES,
    CHAT_PARTY_TYPES,
    CHAT_MESSAGE_KINDS,
    CHAT_BODY_MAX_CHARS,
    CHAT_MAX_ATTACHMENTS,
)
from .known_issues import KnownIssueCategory, KnownIssue, ISSUE_SEVERITIES, ISSUE_STATUSES
from .knowledgebase import KBDocument, KBChunk, KBIngestState, KB_SOURCE_TYPES
from .api_key_reveals import ApiKeyReveal
from .api_keys import ApiKey, ApiKeyTier
from .badge import Badge, PlayerBadge
from .recap import (
    RecapSnapshot,
    RecapDelivery,
    RECAP_SCHEMA_VERSION,
    RECAP_SCOPES,
    DELIVERY_KINDS,
    DELIVERY_DM,
    DELIVERY_CHANNEL,
    DELIVERY_SENT,
    DELIVERY_FORBIDDEN,
    DELIVERY_FAILED,
    SCOPE_GROUP,
    SCOPE_PLAYER,
)
from .clan_log import (
    ClanLogSection,
    ClanLogItem,
    ClanLogFirst,
    CLAN_LOG_SCHEMA_VERSION,
    CLAN_LOG_SOURCES,
    SCOPE_CLAN_LOG,
    PERIOD_ALL,
    SOURCE_DROP,
    SOURCE_CLOG,
    SOURCE_PET,
)
from .subscriptions import (
    SubscriptionTier,
    GroupSubscription,
    SubscriptionPayment,
    UserSubscription,
)
from .events import (
    Event,
    EventWindow,
    EventTask,
    EventTeam,
    EventTeamMember,
    EventSignup,
    EventSignupMessage,
    EventBingoCell,
    EventBingoCompletion,
    EventCompletion,
    EventBuyin,
    EventProgress,
    EventEffort,
    EventChannel,
    EventLeaderVote,
    EventPlayerPoints,
    EventGroup,
    EventGuild,
    EventTeamDiscord,
    EventTaskLibraryItem,
    EventTemplate,
    EventMessageLayout,
    EventType,
    EventTypeTestGroup,
    EventCompetition,
    EventRateLimit,
    EVENT_RATE_LIMIT_ALL_TYPES,
    EventBoardTile,
    EventBoardConfig,
    EventBoardPosition,
    EventCoinLedger,
    BoardgameShopItem,
    EventShopRotation,
    EventTeamInventory,
    EventTeamCooldown,
    EventBoardEffect,
    BOARDGAME_ITEM_TYPES,
    BOARDGAME_EFFECTS,
    BOARDGAME_INVENTORY_STATUSES,
    BOARDGAME_EFFECT_STATUSES,
    EVENT_KINDS,
    EVENT_TASK_DIFFICULTIES,
    EVENT_BOARD_TILE_KINDS,
    EVENT_BOARD_POSITION_STATUSES,
    EVENT_COIN_REASONS,
    EVENT_TASK_TYPES,
    EVENT_TASK_VISIBILITIES,
    EVENT_VISIBILITIES,
    EVENT_TEMPLATE_SCHEMA_VERSION,
    EVENT_FORMATION_MODES,
    EVENT_SELF_SIGNUP_MODES,
    EVENT_MODES,
    EVENT_GROUP_ROLES,
    EVENT_GROUP_STATUSES,
    EVENT_COMPLETION_STATUSES,
    EVENT_BUYIN_KINDS,
    EVENT_BUYIN_STATUSES,
    EVENT_PRIZE_DISTRIBUTIONS,
    EVENT_CHANNEL_KINDS,
    EVENT_BOARD_SIZES,
    EVENT_SUBMISSION_POLICIES,
    EVENT_DISCORD_POLICIES,
    EVENT_PING_KEYS,
    EVENT_TEAM_ROLES,
    EVENT_LEADER_SELECTION_MODES,
    EVENT_TEAM_DISCORD_RETENTIONS,
    EVENT_TEAM_CHANNEL_KINDS,
    EVENT_TASK_PROGRESS_MODES,
    EVENT_MESSAGE_TOGGLE_KEYS,
    EVENT_MESSAGE_LAYOUT_TYPES,
    COMPETITION_EVENT_KINDS,
    COMPETITION_SOURCE_MODES,
)


def get_current_partition() -> int:
    """
        Returns the naming scheme for a partition of drops
        Based on the current month
    """
    now = datetime.now()
    return now.year * 100 + now.month

__all__ = [
    "Base",
    "session",
    "Session",
    "xenforo_engine",
    "XenforoSession",
    "user_group_association",
    "User",
    "NpcList",
    "ItemList",
    "ItemValueOverride",
    "PluginManifestSection",
    "PersonalBestLoadout",
    "GroupComponentLayout",
    "PlayerState",
    "PlayerCollectionLogItem",
    "PlayerCombatAchievementVarps",
    "PlayerQuestState",
    "PlayerDiaryTier",
    "Player",
    "IgnoredPlayer",
    "Group",
    "UserConfiguration",
    "GroupPatreon",
    "Drop",
    "CollectionLogEntry",
    "CombatAchievementEntry",
    "PersonalBestEntry",
    "PlayerPet",
    "QuestCompletionEntry",
    "PlayerDeath",
    "DiaryCompletionEntry",
    "GroupConfiguration",
    "GroupNotification",
    "GroupNotificationBlacklist",
    "GroupNotificationAlwaysList",
    "NotifiedSubmission",
    "NotificationQueue",
    "PlayerNpcKc",
    "PlayerNotificationPrefs",
    "GroupEmbed",
    "GroupSite",
    "GroupSitePage",
    "Field",
    "Guild",
    "GroupWomAssociation",
    "GroupPersonalBestMessage",
    "LBUpdate",
    "Webhook",
    "BackupWebhook",
    "WebhookPendingDeletion",
    "NewWebhook",
    "PlayerItemHourlyTotals",
    "PlayerNpcHourlyTotals",
    "NpcEhbRate",
    "GroupRecentDrops",
    "PlayerDailyAggregates",
    "PlayerLootData",
    "PlayerExperience",
    "HistoricalMetrics",
    "Log",
    "PremiumFeature",
    "FeatureActivation",
    "PointCredit",
    "PointDebit",
    "RecurringPointGrant",
    "get_current_partition",
    "LootboardStyle",
    "Ticket",
    "TicketMessage",
    "PlayerPoints",
    "GroupPointConfig",
    "GroupPointMods",
    "GroupPointTimedEvent",
    "GroupPointBlacklist",
    "GroupPointSeason",
    "VideoUpload",
    "SeasonalDrop",
    "SeasonalPersonalBestEntry",
    "SeasonalCollectionLogEntry",
    "SeasonalCombatAchievementEntry",
    "SeasonalPlayerPet",
    "SeasonalQuestCompletionEntry",
    "DropSplit",
    "GroupAdmin",
    "GroupEventManager",
    "Announcement",
    "AuditLog",
    "DiscordOutbox",
    "DocsPage",
    "SiteRedirect",
    "DevProject",
    "DevTask",
    "DevSubtask",
    "DevNote",
    "PROJECT_STATUSES",
    "TASK_STATUSES",
    "FileTransfer",
    "FileTransferVersion",
    "TRANSFER_MAX_BYTES",
    "TRANSFER_RETENTION_DAYS",
    "TRANSFER_UPLOADER_ROLES",
    "ChatThread",
    "ChatParticipant",
    "ChatMessage",
    "ChatRead",
    "SurfaceRead",
    "GroupNotice",
    "CHAT_THREAD_KINDS",
    "CHAT_THREAD_STATUSES",
    "CHAT_PARTY_TYPES",
    "CHAT_MESSAGE_KINDS",
    "CHAT_BODY_MAX_CHARS",
    "CHAT_MAX_ATTACHMENTS",
    "KnownIssueCategory",
    "KnownIssue",
    "ISSUE_SEVERITIES",
    "ISSUE_STATUSES",
    "Suggestion",
    "SuggestionMessage",
    "KBDocument",
    "KBChunk",
    "KBIngestState",
    "KB_SOURCE_TYPES",
    "Badge",
    "RecapSnapshot",
    "RecapDelivery",
    "RECAP_SCHEMA_VERSION",
    "RECAP_SCOPES",
    "DELIVERY_KINDS",
    "DELIVERY_DM",
    "DELIVERY_CHANNEL",
    "DELIVERY_SENT",
    "DELIVERY_FORBIDDEN",
    "DELIVERY_FAILED",
    "SCOPE_GROUP",
    "SCOPE_PLAYER",
    "ClanLogSection",
    "ClanLogItem",
    "ClanLogFirst",
    "CLAN_LOG_SCHEMA_VERSION",
    "CLAN_LOG_SOURCES",
    "SCOPE_CLAN_LOG",
    "PERIOD_ALL",
    "SOURCE_DROP",
    "SOURCE_CLOG",
    "SOURCE_PET",
    "PlayerBadge",
    "SubscriptionTier",
    "GroupSubscription",
    "SubscriptionPayment",
    "UserSubscription",
    "Event",
    "EventWindow",
    "EventTask",
    "EventTeam",
    "EventTeamMember",
    "EventSignup",
    "EventSignupMessage",
    "EventBingoCell",
    "EventBingoCompletion",
    "EventCompletion",
    "EventBuyin",
    "EventProgress",
    "EventEffort",
    "EventChannel",
    "EventLeaderVote",
    "EventPlayerPoints",
    "EventGroup",
    "EventGuild",
    "EventTeamDiscord",
    "EventTaskLibraryItem",
    "EventTemplate",
    "EventMessageLayout",
    "EventType",
    "EventTypeTestGroup",
    "EventCompetition",
    "EventRateLimit",
    "EVENT_RATE_LIMIT_ALL_TYPES",
    "EventBoardTile",
    "EventBoardConfig",
    "EventBoardPosition",
    "EventCoinLedger",
    "BoardgameShopItem",
    "EventShopRotation",
    "EventTeamInventory",
    "EventTeamCooldown",
    "EventBoardEffect",
    "BOARDGAME_ITEM_TYPES",
    "BOARDGAME_EFFECTS",
    "BOARDGAME_INVENTORY_STATUSES",
    "BOARDGAME_EFFECT_STATUSES",
    "EVENT_KINDS",
    "EVENT_TASK_DIFFICULTIES",
    "EVENT_BOARD_TILE_KINDS",
    "EVENT_BOARD_POSITION_STATUSES",
    "EVENT_COIN_REASONS",
    "EVENT_TEMPLATE_SCHEMA_VERSION",
    "EVENT_TASK_TYPES",
    "EVENT_TASK_VISIBILITIES",
    "EVENT_VISIBILITIES",
    "EVENT_FORMATION_MODES",
    "EVENT_SELF_SIGNUP_MODES",
    "EVENT_MODES",
    "EVENT_GROUP_ROLES",
    "EVENT_GROUP_STATUSES",
    "EVENT_COMPLETION_STATUSES",
    "EVENT_BUYIN_KINDS",
    "EVENT_BUYIN_STATUSES",
    "EVENT_PRIZE_DISTRIBUTIONS",
    "EVENT_CHANNEL_KINDS",
    "EVENT_DISCORD_POLICIES",
    "EVENT_PING_KEYS",
    "EVENT_TEAM_ROLES",
    "EVENT_LEADER_SELECTION_MODES",
    "EVENT_TEAM_DISCORD_RETENTIONS",
    "EVENT_TEAM_CHANNEL_KINDS",
    "DropGroupModeration",
    "COUNTING_STATUSES",
    "EXCLUDING_STATUSES",
    "UNDOABLE_STATUSES",
    "EVENT_BOARD_SIZES",
    "EVENT_SUBMISSION_POLICIES",
    "EVENT_TASK_PROGRESS_MODES",
    "EVENT_MESSAGE_TOGGLE_KEYS",
    "EVENT_MESSAGE_LAYOUT_TYPES",
    "COMPETITION_EVENT_KINDS",
    "COMPETITION_SOURCE_MODES",
]
