"""Event model changes.

Revision ID: 042293692555
Revises: e7fde0b7b0f1
Create Date: 2025-06-01 09:59:18.636965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '042293692555'
down_revision: Union[str, None] = 'e7fde0b7b0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('bingo_board_tiles', sa.Column('assigned_id', sa.Integer(), nullable=True))
    op.drop_constraint('bingo_board_tiles_ibfk_3', 'bingo_board_tiles', type_='foreignkey')
    op.create_foreign_key(None, 'bingo_board_tiles', 'assigned_tasks', ['assigned_id'], ['id'])
    op.create_foreign_key(None, 'bingo_board_tiles', 'base_tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bingo_board_tiles', type_='foreignkey')
    op.drop_constraint(None, 'bingo_board_tiles', type_='foreignkey')
    op.create_foreign_key('bingo_board_tiles_ibfk_3', 'bingo_board_tiles', 'assigned_tasks', ['task_id'], ['id'])
    op.drop_column('bingo_board_tiles', 'assigned_id')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
