"""Add groupPoint models

Revision ID: 0790d4d64be1
Revises: d6ddea7891e2
Create Date: 2025-10-26 05:33:28.095795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0790d4d64be1'
down_revision: Union[str, None] = 'd6ddea7891e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_point_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=125), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('divisor', sa.Integer(), nullable=False),
    sa.Column('can_modify', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
