"""Event model changes.

Revision ID: 0b69d0b62230
Revises: c72012d0e0c8
Create Date: 2025-05-26 12:38:23.947492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b69d0b62230'
down_revision: Union[str, None] = 'c72012d0e0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('base_tasks', sa.Column('task_type', sa.Enum('ITEM_COLLECTION', 'KC_TARGET', 'XP_TARGET', 'EHP_TARGET', 'EHB_TARGET', 'LOOT_VALUE', 'CUSTOM', name='tasktype'), nullable=False))
    op.add_column('base_tasks', sa.Column('task_config', sa.JSON(), nullable=True))
    op.add_column('base_tasks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('base_tasks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('base_tasks', 'description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_column('event_tasks', 'is_assembly')
    op.drop_column('event_tasks', 'assembly_id')
    op.add_column('tracked_task_data', sa.Column('assigned_task_id', sa.Integer(), nullable=False))
    op.drop_constraint('tracked_task_data_ibfk_3', 'tracked_task_data', type_='foreignkey')
    op.create_foreign_key(None, 'tracked_task_data', 'assigned_tasks', ['assigned_task_id'], ['id'])
    op.drop_column('tracked_task_data', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_task_data', sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tracked_task_data', type_='foreignkey')
    op.create_foreign_key('tracked_task_data_ibfk_3', 'tracked_task_data', 'event_tasks', ['task_id'], ['id'])
    op.drop_column('tracked_task_data', 'assigned_task_id')
    op.add_column('event_tasks', sa.Column('assembly_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('event_tasks', sa.Column('is_assembly', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('base_tasks', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('base_tasks', 'created_by')
    op.drop_column('base_tasks', 'is_active')
    op.drop_column('base_tasks', 'task_config')
    op.drop_column('base_tasks', 'task_type')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
