"""auto migration

Revision ID: 0d54df986bac
Revises: 849f3052990d
Create Date: 2025-09-14 12:09:48.832421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d54df986bac'
down_revision: Union[str, None] = '849f3052990d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Add drops.unique_id if missing, using MySQL instant add to minimize locking when possible
    existing_drop_columns = {col['name'] for col in inspector.get_columns('drops')}
    if 'unique_id' not in existing_drop_columns:
        if bind.dialect.name == 'mysql':
            # Prefer instant add to avoid long metadata locks on busy tables (MySQL 8+)
            try:
                op.execute(sa.text(
                    "ALTER TABLE drops ALGORITHM=INSTANT, LOCK=NONE ADD COLUMN IF NOT EXISTS unique_id VARCHAR(255) NULL"
                ))
            except Exception:
                # Fallback if IF NOT EXISTS or INSTANT not supported
                op.add_column('drops', sa.Column('unique_id', sa.String(length=255), nullable=True))
        else:
            op.add_column('drops', sa.Column('unique_id', sa.String(length=255), nullable=True))

    # Add personal_best.unique_id if missing
    existing_pb_columns = {col['name'] for col in inspector.get_columns('personal_best')}
    if 'unique_id' not in existing_pb_columns:
        if bind.dialect.name == 'mysql':
            try:
                op.execute(sa.text(
                    "ALTER TABLE personal_best ALGORITHM=INSTANT, LOCK=NONE ADD COLUMN IF NOT EXISTS unique_id VARCHAR(255) NULL"
                ))
            except Exception:
                op.add_column('personal_best', sa.Column('unique_id', sa.String(length=255), nullable=True))
        else:
            op.add_column('personal_best', sa.Column('unique_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'mysql':
        try:
            op.execute(sa.text(
                "ALTER TABLE personal_best DROP COLUMN IF EXISTS unique_id"
            ))
        except Exception:
            op.drop_column('personal_best', 'unique_id')
        try:
            op.execute(sa.text(
                "ALTER TABLE drops DROP COLUMN IF EXISTS unique_id"
            ))
        except Exception:
            op.drop_column('drops', 'unique_id')
    else:
        op.drop_column('personal_best', 'unique_id')
        op.drop_column('drops', 'unique_id')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
