"""autogen

Revision ID: 1a6e66e2e318
Revises: b7c8d9e0f1a2
Create Date: 2026-02-09 22:14:24.117902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a6e66e2e318'
down_revision: Union[str, None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_point_mods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=125), nullable=False),
    sa.Column('award', sa.Integer(), nullable=False),
    sa.Column('divisor', sa.Integer(), nullable=False),
    sa.Column('can_modify', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    
    op.drop_table('group_point_mods')
    # ### end Alembic commands ###
