"""Event model changes.

Revision ID: 20950abea623
Revises: e9ceedc7f9db
Create Date: 2025-05-26 08:28:44.300183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20950abea623'
down_revision: Union[str, None] = 'e9ceedc7f9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('event_tasks', sa.Column('task_type', sa.Enum('ITEM_COLLECTION', 'KC_TARGET', 'XP_TARGET', 'EHP_TARGET', 'EHB_TARGET', 'LOOT_VALUE', 'TIME_BASED', 'CUSTOM', name='tasktype'), nullable=False))
    op.add_column('event_tasks', sa.Column('task_config', sa.JSON(), nullable=True))
    op.add_column('event_tasks', sa.Column('is_assembly', sa.Boolean(), nullable=False))
    op.add_column('event_tasks', sa.Column('assembly_id', sa.Integer(), nullable=True))
    op.alter_column('event_tasks', 'description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_tasks', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('event_tasks', 'assembly_id')
    op.drop_column('event_tasks', 'is_assembly')
    op.drop_column('event_tasks', 'task_config')
    op.drop_column('event_tasks', 'task_type')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
