"""Event model updates.

Revision ID: 209ec1685733
Revises: 4b2fdb7bf91d
Create Date: 2025-06-02 12:06:18.399060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '209ec1685733'
down_revision: Union[str, None] = '4b2fdb7bf91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_tasks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('tracked_task_data', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_task_data', 'is_active')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('assigned_tasks', 'is_active')
    # ### end Alembic commands ###
