"""Event model updates

Revision ID: 262385e9df48
Revises: 8c591955ca8a
Create Date: 2025-05-24 15:30:13.154207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '262385e9df48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_boards',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('bingo_games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('individual_boards', sa.Boolean(), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('win_condition', sa.String(length=50), nullable=False),
    sa.Column('allow_diagonal', sa.Boolean(), nullable=False),
    sa.Column('center_free', sa.Boolean(), nullable=False),
    sa.Column('max_boards_per_team', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('assigned_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['event_tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['event_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bingo_board_tiles',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_by_team_id', sa.Integer(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['bingo_boards.board_id'], ),
    sa.ForeignKeyConstraint(['completed_by_team_id'], ['event_teams.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['event_tasks.id'], ),
    sa.PrimaryKeyConstraint('tile_id')
    )
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('board_game', 'die_sides',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('board_game', 'total_tiles',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('event_configurations', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('event_configurations', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('event_items', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_items', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_participants', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_participants', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_participants', 'points',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('event_tasks', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('event_tasks', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('event_tasks', 'difficulty',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('event_tasks', 'required_items',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('event_tasks', 'date_added',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('event_tasks', 'date_updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('event_tasks', 'assembly_id')
    op.drop_column('event_tasks', 'type')
    op.drop_column('event_tasks', 'is_assembly')
    op.alter_column('event_team_cooldowns', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('event_team_cooldowns', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_effects', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('event_team_effects', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_inventory', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_inventory', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_teams', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_teams', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_teams', 'mercy_rule',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('event_teams', 'assembled_items')
    op.alter_column('events', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('events', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.add_column('event_teams', sa.Column('assembled_items', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('event_teams', 'mercy_rule',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('event_teams', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_teams', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_inventory', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_team_inventory', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_effects', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_effects', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('event_team_cooldowns', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_team_cooldowns', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('event_tasks', sa.Column('is_assembly', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('event_tasks', sa.Column('type', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('event_tasks', sa.Column('assembly_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('event_tasks', 'date_updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('event_tasks', 'date_added',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('event_tasks', 'required_items',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('event_tasks', 'difficulty',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('event_tasks', 'description',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('event_tasks', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('event_participants', 'points',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('event_participants', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_participants', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_items', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'0000-00-00 00:00:00'"))
    op.alter_column('event_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('event_configurations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('event_configurations', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('board_game', 'total_tiles',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('board_game', 'die_sides',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('bingo_board_tiles')
    op.drop_table('assigned_tasks')
    op.drop_table('bingo_games')
    op.drop_table('bingo_boards')
    # ### end Alembic commands ###
