"""Add points models (no circular FK)

Revision ID: 3c256d54ab7a
Revises: 6dd21172c0b6
Create Date: 2025-08-31 13:01:49.691020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c256d54ab7a'
down_revision: Union[str, None] = '6dd21172c0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premium_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('scope', sa.Enum('player', 'group', 'both'), server_default=sa.text("'both'"), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_features_key'), 'premium_features', ['key'], unique=True)
    op.create_table('feature_activations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['premium_features.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activation_owner', 'feature_activations', ['player_id', 'group_id'], unique=False)
    op.create_index('idx_activation_status', 'feature_activations', ['status'], unique=False)
    op.create_table('point_credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('subscription', 'nitro', 'ingame', 'admin'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_remaining', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_expires', 'point_credits', ['expires_at'], unique=False)
    op.create_index('idx_credit_owner', 'point_credits', ['player_id', 'group_id'], unique=False)
    op.create_index('idx_credit_status', 'point_credits', ['status'], unique=False)
    op.create_table('point_debits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('spent_by_player_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('feature_activation', 'manual'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.Column('feature_activation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_activation_id'], ['feature_activations.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['spent_by_player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debit_owner', 'point_debits', ['player_id', 'group_id', 'created_at'], unique=False)
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('idx_debit_owner', table_name='point_debits')
    op.drop_table('point_debits')
    op.drop_index('idx_credit_status', table_name='point_credits')
    op.drop_index('idx_credit_owner', table_name='point_credits')
    op.drop_index('idx_credit_expires', table_name='point_credits')
    op.drop_table('point_credits')
    op.drop_index('idx_activation_status', table_name='feature_activations')
    op.drop_index('idx_activation_owner', table_name='feature_activations')
    op.drop_table('feature_activations')
    op.drop_index(op.f('ix_premium_features_key'), table_name='premium_features')
    op.drop_table('premium_features')
    # ### end Alembic commands ###
