"""autogenerate upgrade

Revision ID: 419c0ed7574e
Revises: 0790d4d64be1
Create Date: 2025-12-02 09:07:52.994370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '419c0ed7574e'
down_revision: Union[str, None] = '0790d4d64be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_pets', sa.Column('unique_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_pets', 'unique_id')
    