"""autogenerated upgrade

Revision ID: 42ad2e3cd416
Revises: 3c256d54ab7a
Create Date: 2025-09-03 16:16:29.337047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '42ad2e3cd416'
down_revision: Union[str, None] = '3c256d54ab7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point_credits', 'source',
               existing_type=mysql.ENUM('subscription', 'nitro', 'ingame', 'admin'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point_credits', 'source',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('subscription', 'nitro', 'ingame', 'admin'),
               existing_nullable=False)
    # ### end Alembic commands ###
