"""Event model changes.

Revision ID: 487073074593
Revises: 042293692555
Create Date: 2025-06-01 11:22:26.177849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '487073074593'
down_revision: Union[str, None] = '042293692555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('bingo_games', 'allow_diagonal')
    op.drop_column('bingo_games', 'max_boards_per_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bingo_games', sa.Column('max_boards_per_team', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('bingo_games', sa.Column('allow_diagonal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
