"""define whether submissions caem from api

Revision ID: 5698c3f386e9
Revises: 332bde580584
Create Date: 2025-06-23 10:32:10.108076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5698c3f386e9'
down_revision: Union[str, None] = '332bde580584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('collection', sa.Column('used_api', sa.Boolean(), nullable=True))
    op.add_column('combat_achievement', sa.Column('used_api', sa.Boolean(), nullable=True))
    op.add_column('drops', sa.Column('used_api', sa.Boolean(), nullable=True))
    op.add_column('personal_best', sa.Column('used_api', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_best', 'used_api')
    op.drop_column('drops', 'used_api')
    op.drop_column('combat_achievement', 'used_api')
    op.drop_column('collection', 'used_api')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
