"""auto migration

Revision ID: 6d599081fc8e
Revises: 419c0ed7574e
Create Date: 2026-01-16 00:55:17.684320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d599081fc8e'
down_revision: Union[str, None] = '419c0ed7574e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('player_pets', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_pets', 'date_added')
    