"""autogenerated migration

Revision ID: 6fea10300978
Revises: b22832bc3602
Create Date: 2025-08-15 10:26:55.646172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fea10300978'
down_revision: Union[str, None] = 'b22832bc3602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wom_group_member_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_wom_id', sa.Integer(), nullable=False),
    sa.Column('group_dt_id', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('wom_group_member_ids')
    # ### end Alembic commands ###
