"""Add team_id to bingo_boards

Revision ID: a4b234a63ca0
Revises: 615e23a5099f
Create Date: 2025-05-24 16:10:11.848151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4b234a63ca0'
down_revision: Union[str, None] = '615e23a5099f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('bingo_board_tiles_ibfk_3', 'bingo_board_tiles', type_='foreignkey')
    op.create_foreign_key(None, 'bingo_board_tiles', 'assigned_tasks', ['task_id'], ['id'])
    op.add_column('bingo_boards', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bingo_boards', 'event_teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bingo_boards', type_='foreignkey')
    op.drop_column('bingo_boards', 'team_id')
    op.drop_constraint(None, 'bingo_board_tiles', type_='foreignkey')
    op.create_foreign_key('bingo_board_tiles_ibfk_3', 'bingo_board_tiles', 'event_tasks', ['task_id'], ['id'])
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
