"""Add new materialized view tables

Revision ID: b22832bc3602
Revises: 888469992433
Create Date: 2025-07-20 09:59:38.939442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b22832bc3602'
down_revision: Union[str, None] = '888469992433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_daily_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('drop_count', sa.Integer(), nullable=True),
    sa.Column('unique_items', sa.Integer(), nullable=True),
    sa.Column('unique_npcs', sa.Integer(), nullable=True),
    sa.Column('last_drop_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'date', 'partition', name='uq_player_daily_agg')
    )
    op.create_index('idx_partition_date', 'player_daily_aggregates', ['partition', 'date'], unique=False)
    op.create_index('idx_player_date', 'player_daily_aggregates', ['player_id', 'date'], unique=False)
    op.create_table('player_exp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('defence', sa.Integer(), nullable=False),
    sa.Column('ranged', sa.Integer(), nullable=False),
    sa.Column('prayer', sa.Integer(), nullable=False),
    sa.Column('magic', sa.Integer(), nullable=False),
    sa.Column('runecraft', sa.Integer(), nullable=False),
    sa.Column('hitpoints', sa.Integer(), nullable=False),
    sa.Column('crafting', sa.Integer(), nullable=False),
    sa.Column('mining', sa.Integer(), nullable=False),
    sa.Column('smithing', sa.Integer(), nullable=False),
    sa.Column('woodcutting', sa.Integer(), nullable=False),
    sa.Column('farming', sa.Integer(), nullable=False),
    sa.Column('firemaking', sa.Integer(), nullable=False),
    sa.Column('fishing', sa.Integer(), nullable=False),
    sa.Column('hunter', sa.Integer(), nullable=False),
    sa.Column('herblore', sa.Integer(), nullable=False),
    sa.Column('cooking', sa.Integer(), nullable=False),
    sa.Column('thieving', sa.Integer(), nullable=False),
    sa.Column('construction', sa.Integer(), nullable=False),
    sa.Column('slayer', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('fletching', sa.Integer(), nullable=False),
    sa.Column('sailing', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_item_hourly_totals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('date_hour', sa.String(length=13), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('drop_count', sa.Integer(), nullable=True),
    sa.Column('last_drop_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'item_id', 'date_hour', 'partition', name='uq_player_item_hourly')
    )
    op.create_index('idx_item_date_hour', 'player_item_hourly_totals', ['item_id', 'date_hour'], unique=False)
    op.create_index('idx_partition_date_hour', 'player_item_hourly_totals', ['partition', 'date_hour'], unique=False)
    op.create_index('idx_player_date_hour', 'player_item_hourly_totals', ['player_id', 'date_hour'], unique=False)
    op.create_table('player_npc_hourly_totals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('date_hour', sa.String(length=13), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('drop_count', sa.Integer(), nullable=True),
    sa.Column('last_drop_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['npc_id'], ['npc_list.npc_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'npc_id', 'date_hour', 'partition', name='uq_player_npc_hourly')
    )
    op.create_index('idx_npc_date_hour', 'player_npc_hourly_totals', ['npc_id', 'date_hour'], unique=False)
    op.create_index('idx_partition_date_hour', 'player_npc_hourly_totals', ['partition', 'date_hour'], unique=False)
    op.create_index('idx_player_npc_date_hour', 'player_npc_hourly_totals', ['player_id', 'npc_id', 'date_hour'], unique=False)
    op.create_table('group_recent_drops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('drop_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drop_id'], ['drops.drop_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc_list.npc_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_added', 'group_recent_drops', ['date_added'], unique=False)
    op.create_index('idx_group_date', 'group_recent_drops', ['group_id', 'date_added'], unique=False)
    op.create_index('idx_group_partition', 'group_recent_drops', ['group_id', 'partition'], unique=False)
    op.create_index('idx_player_date', 'group_recent_drops', ['player_id', 'date_added'], unique=False)
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('idx_player_date', table_name='group_recent_drops')
    op.drop_index('idx_group_partition', table_name='group_recent_drops')
    op.drop_index('idx_group_date', table_name='group_recent_drops')
    op.drop_index('idx_date_added', table_name='group_recent_drops')
    op.drop_table('group_recent_drops')
    op.drop_index('idx_player_npc_date_hour', table_name='player_npc_hourly_totals')
    op.drop_index('idx_partition_date_hour', table_name='player_npc_hourly_totals')
    op.drop_index('idx_npc_date_hour', table_name='player_npc_hourly_totals')
    op.drop_table('player_npc_hourly_totals')
    op.drop_index('idx_player_date_hour', table_name='player_item_hourly_totals')
    op.drop_index('idx_partition_date_hour', table_name='player_item_hourly_totals')
    op.drop_index('idx_item_date_hour', table_name='player_item_hourly_totals')
    op.drop_table('player_item_hourly_totals')
    op.drop_table('player_exp')
    op.drop_index('idx_player_date', table_name='player_daily_aggregates')
    op.drop_index('idx_partition_date', table_name='player_daily_aggregates')
    op.drop_table('player_daily_aggregates')
    # ### end Alembic commands ###
