"""Adjust image_url length

Revision ID: c29d1c68359c
Revises: f53252ea4ae5
Create Date: 2025-09-20 21:45:52.378385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c29d1c68359c'
down_revision: Union[str, None] = 'f53252ea4ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('collection', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('combat_achievement', 'image_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('personal_best', 'image_url',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_best', 'image_url',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('combat_achievement', 'image_url',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('collection', 'image_url',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
