"""Event model changes.

Revision ID: cbc916483a55
Revises: 20950abea623
Create Date: 2025-05-26 11:12:35.973473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbc916483a55'
down_revision: Union[str, None] = '20950abea623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_task_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ITEM_COLLECTION', 'KC_TARGET', 'XP_TARGET', 'EHP_TARGET', 'EHB_TARGET', 'LOOT_VALUE', 'TIME_BASED', 'CUSTOM', name='tasktype'), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['event_participants.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['event_tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['event_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('tracked_task_data')
    # ### end Alembic commands ###
