"""Event model changes.

Revision ID: e7fde0b7b0f1
Revises: 0b69d0b62230
Create Date: 2025-06-01 07:51:58.075609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import Session
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'e7fde0b7b0f1'
down_revision: Union[str, None] = '0b69d0b62230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get database connection
    connection = op.get_bind()
    session = Session(bind=connection)
    
    try:
        # First, identify and delete duplicate notifications
        # Keep the most recent one for each unique combination
        cleanup_query = """
        DELETE n1 FROM notification_queue n1
        INNER JOIN notification_queue n2
        WHERE n1.notification_type = n2.notification_type
        AND n1.player_id = n2.player_id
        AND n1.group_id = n2.group_id
        AND n1.data = n2.data
        AND n1.id < n2.id
        """
        
        session.execute(text(cleanup_query))
        session.commit()
        
        # Now proceed with the original migration
        op.alter_column('backup_webhooks', 'webhook_id',
                   existing_type=mysql.VARCHAR(length=255),
                   nullable=True)
        
        # Add the unique constraint after cleaning up duplicates
        op.create_unique_constraint('uix_notification_unique', 'notification_queue', 
                                  ['notification_type', 'player_id', 'group_id', 'data'])
        
    except Exception as e:
        session.rollback()
        raise e
    finally:
        session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_notification_unique', 'notification_queue', type_='unique')
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
