"""Added player_loot_data

Revision ID: f1542e783c15
Revises: 5698c3f386e9
Create Date: 2025-07-04 11:42:53.040761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1542e783c15'
down_revision: Union[str, None] = '5698c3f386e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_loot_data',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('player_loot_data')
    # ### end Alembic commands ###
