"""Adjust image_url length in drops table

Revision ID: f53252ea4ae5
Revises: 0d54df986bac
Create Date: 2025-09-20 21:39:59.946394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f53252ea4ae5'
down_revision: Union[str, None] = '0d54df986bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('drops', 'image_url',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drops', 'image_url',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('backup_webhooks', 'webhook_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
