"""Item and NPC glyphs — the game's own art, as Discord application emoji.

Discord has no inline-image primitive. An embed thumbnail, a Components V2
accessory and a media gallery all sit *beside* a line, never inside it, so the
only way to put an item icon into a sentence is to make it an emoji. That is
what this is: the ~1000 items and NPCs that DropTracker notifications actually
mention, uploaded as **application** emoji so they render in every channel the
bot can already speak in — no ``USE_EXTERNAL_EMOJIS``, no emoji-server farm, and
2000 per app instead of 250 per guild (see :mod:`utils.app_emojis` for why guild
emoji were abandoned).

Three files, three jobs:

* ``data/game_emojis.json`` — the **manifest**: which entities are in the set,
  their canonical name, their source id, and the emoji name they own. Committed,
  regenerated by ``scripts/rank_game_emojis.py`` from notification history.
* ``static/game_emojis.json`` — the **map**: ``{profile: {key: "<:name:id>"}}``,
  written by ``scripts/seed_game_emojis.py`` after it uploads. Committed too, so
  a fresh checkout renders without a seeding run.
* this module — the read side, and the single definition of how a name becomes
  a key and a key becomes an emoji name. Both scripts import it so the three can
  not drift.

Lookups are by **name or id**, because callers have whichever the payload gave
them: a drop notification carries ``item_name`` and a ``drop`` row carries
``item_id``. NPC names go through :func:`utils.npc_names.npc_match_key`, the
codebase's one spelling-insensitive NPC identity rule, so "The Gauntlet" and
"Crystalline Hunllef" resolve to the same glyph.

Every lookup returns ``None`` when the entity is not in the set, which is the
normal path — the set is a budget, not a catalogue, and 28k items are outside
it. Callers render the line without a glyph rather than with a broken one; there
is no Unicode fallback here because no emoji stands in for "Twisted bow".

Deliberately pure: stdlib only at import time, no DB and no network, so the
bots, the notification service, the lootboard generator and the tests can all
import it.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Optional

from utils.npc_names import npc_match_key

_ROOT = Path(__file__).resolve().parent.parent

#: Committed. Which entities are in the set — written by scripts/rank_game_emojis.py.
MANIFEST_PATH = _ROOT / "data" / "game_emojis.json"

#: Committed. {profile: {key: "<:name:id>"}} — written by scripts/seed_game_emojis.py.
MAP_PATH = _ROOT / "static" / "game_emojis.json"

#: Where the seeder reads art from. Item icons come from RuneLite's cache and
#: NPC renders from the wiki; both are already on disk for the whole catalogue
#: (see scripts/backfill_item_images.py and backfill_npc_images.py).
ITEM_ART_DIR = _ROOT / "static" / "assets" / "img" / "itemdb"
NPC_ART_DIR = _ROOT / "static" / "assets" / "img" / "npcdb"

#: Emoji-name prefixes. These are what keep three independently-seeded sets
#: apart on one application: ``rank_*`` (utils/rank_emojis), the unprefixed UI
#: keys (utils/app_emojis), and these. Each seeder's --prune only considers its
#: own namespace, so an unprefixed set would be deleted by the next run of
#: another seeder.
ITEM_PREFIX = "item_"
NPC_PREFIX = "npc_"

#: Discord's rule for an emoji name.
MAX_EMOJI_NAME = 32
_VALID_NAME = re.compile(r"^[A-Za-z0-9_]{2,32}$")

#: Profile -> the .env key holding that application's bot token, same contract
#: as utils.app_emojis.PROFILE_TOKENS. An app emoji renders only for the app
#: that owns it, so the map is keyed by profile and each process declares its
#: own at startup.
PROFILE_TOKENS = {
    "core": "BOT_TOKEN",
    "core-dev": "DEV_TOKEN",
}

DEFAULT_PROFILE = "core"

_NON_KEY = re.compile(r"[^a-z0-9]+")

_state = {"profile": os.getenv("DROPTRACKER_EMOJI_PROFILE") or DEFAULT_PROFILE}
_map_cache = {"mtime": None, "map": {}}
_manifest_cache = {"mtime": None, "manifest": None, "index": None}


# --------------------------------------------------------------------------
# keys and names
# --------------------------------------------------------------------------

def item_key(name) -> str:
    """Item name → the key every source agrees on.

    Lowercased with non-alphanumeric runs collapsed, so ``"Zenyte shard"``,
    ``"zenyte shard"`` and a stray double space all land on ``zenyte_shard``.
    Parentheses collapse too, which deliberately merges ``"Weapon poison(++)"``
    into ``"weapon_poison"`` — they are one icon's worth of difference and the
    manifest keeps only one of them.
    """
    return _NON_KEY.sub("_", str(name or "").strip().lower()).strip("_")


def npc_key(name) -> str:
    """NPC name → key, via the codebase's one NPC identity rule.

    :func:`utils.npc_names.npc_match_key` folds spelling, the leading article
    and known aliases; this only swaps its ``-`` separators for the ``_`` a
    Discord emoji name allows.
    """
    return npc_match_key(name).replace("-", "_")


#: A trailing "(...)" in an OSRS item name is almost always the *discriminator*
#: — "(uncharged)", "(saradomin)", "(g)", "(t)", "(broken)" — so it is the last
#: thing that should be trimmed away, even though it is at the end.
_QUALIFIER = re.compile(r"\s*\(([^()]+)\)\s*$")


def emoji_name(kind: str, name) -> str:
    """The Discord emoji name for an entity, prefixed and length-clamped.

    Discord allows 32 characters and 46 real item names are longer than that
    with the prefix on. Naive truncation is worse than it looks here, because
    OSRS puts the distinguishing word *last*: the three "Rune scimitar ornament
    kit (saradomin/guthix/zamorak)" all truncate to the same 32 characters and
    end up as ``..._ki``, ``..._ki_2``, ``..._ki_3``. So a trailing qualifier is
    reserved first and the stem is trimmed at a word boundary to fit around it.

    Uniqueness across the set is the manifest builder's job, not this
    function's: two entities can still legally produce one name, and it resolves
    that clash with a numeric suffix.
    """
    prefix = ITEM_PREFIX if kind == "item" else NPC_PREFIX
    text = str(name or "").strip()
    qualifier = ""
    match = _QUALIFIER.search(text) if kind == "item" else None
    if match:
        qualifier = item_key(match.group(1))
        text = text[:match.start()]
    body = item_key(text) if kind == "item" else npc_key(text)
    room = MAX_EMOJI_NAME - len(prefix) - (len(qualifier) + 1 if qualifier else 0)
    if len(body) > room:
        trimmed = body[:max(room, 0)]
        # Cut back to the last complete word, but never to something so short it
        # stops being recognisable — a stem is worth more than a qualifier.
        cut = trimmed.rfind("_")
        body = trimmed[:cut] if cut >= room // 2 else trimmed
    parts = [p for p in (body, qualifier) if p]
    return f"{prefix}{'_'.join(parts)}"[:MAX_EMOJI_NAME].rstrip("_")


def is_valid_emoji_name(name) -> bool:
    """Whether Discord would accept this as an emoji name."""
    return bool(_VALID_NAME.match(str(name or "")))


# --------------------------------------------------------------------------
# profile
# --------------------------------------------------------------------------

def use_profile(profile: str) -> None:
    """Declare which application this process is running as.

    An app emoji renders only for the app that owns it, so a process posting
    ids from another profile emits raw ``<:item_twisted_bow:...>`` text. Each
    bot calls this once before connecting.
    """
    _state["profile"] = str(profile or DEFAULT_PROFILE)


def current_profile() -> str:
    """The profile this process resolves against."""
    return _state["profile"]


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------

def load_manifest(path=None) -> dict:
    """The manifest, memoized on mtime. ``{"items": [...], "npcs": [...]}``.

    A missing file is not an error — it means the ranking script has never run
    here, and every lookup returns None.
    """
    path = Path(path or MANIFEST_PATH)
    try:
        mtime = os.path.getmtime(path)
    except OSError:
        _manifest_cache.update(mtime=None, manifest={"items": [], "npcs": []}, index=None)
        return _manifest_cache["manifest"]
    if _manifest_cache["mtime"] != mtime:
        try:
            data = json.loads(Path(path).read_text(encoding="utf-8"))
            manifest = {
                "items": list(data.get("items") or []),
                "npcs": list(data.get("npcs") or []),
                "criteria": data.get("criteria") or {},
            }
        except (OSError, ValueError):
            manifest = {"items": [], "npcs": [], "criteria": {}}
        _manifest_cache.update(mtime=mtime, manifest=manifest, index=None)
    return _manifest_cache["manifest"]


def _index() -> dict:
    """``{kind: {"by_key": {...}, "by_id": {...}}}`` over the manifest.

    ``by_id`` maps *every* id an entry claims, not just its art id: noted and
    placeholder item ids share a name and must share the glyph, or a noted drop
    renders blank while the un-noted one renders.
    """
    manifest = load_manifest()
    if _manifest_cache["index"] is None:
        index = {}
        for kind, entries in (("item", manifest["items"]), ("npc", manifest["npcs"])):
            by_key, by_id = {}, {}
            for entry in entries:
                by_key[entry["key"]] = entry
                for entity_id in entry.get("ids") or [entry.get("id")]:
                    if entity_id is not None:
                        by_id[int(entity_id)] = entry
            index[kind] = {"by_key": by_key, "by_id": by_id}
        _manifest_cache["index"] = index
    return _manifest_cache["index"]


def load_map(path=None) -> dict:
    """``{profile: {kind: {key: "<:name:id>"}}}``, memoized on mtime.

    Nested by kind rather than flat like the rank and UI maps, because a clog
    *source* is often also an item and the two share a key: "Unsired", "Bird
    nest" and "Intricate pouch" each exist in both ``items`` and ``npc_list``. A
    flat map hands whichever was written second to both.

    Missing means the seeder has not run against this app yet; every lookup
    returns None and callers render without a glyph.
    """
    path = Path(path or MAP_PATH)
    try:
        mtime = os.path.getmtime(path)
    except OSError:
        _map_cache.update(mtime=None, map={})
        return {}
    if _map_cache["mtime"] != mtime:
        try:
            data = json.loads(Path(path).read_text(encoding="utf-8"))
            _map_cache["map"] = {
                str(profile): {
                    str(kind): {str(k): v for k, v in (entries or {}).items() if v}
                    for kind, entries in (kinds or {}).items()
                    if isinstance(entries, dict)
                }
                for profile, kinds in (data or {}).items()
                if isinstance(kinds, dict)
            }
        except (OSError, ValueError):
            _map_cache["map"] = {}
        _map_cache["mtime"] = mtime
    return _map_cache["map"]


# --------------------------------------------------------------------------
# lookups
# --------------------------------------------------------------------------

def _lookup(kind: str, key: str, profile=None) -> Optional[str]:
    """The ``<:name:id>`` for one entity, or None.

    Both files have to agree: the manifest says the entity is in the set, the
    map says this application actually owns the emoji. A key present in one but
    not the other means a rank/seed run is half-done, and the honest answer is
    no glyph rather than a broken reference.
    """
    if not key:
        return None
    if key not in _index()[kind]["by_key"]:
        return None
    profiles = load_map().get(profile or current_profile()) or {}
    return (profiles.get(kind) or {}).get(key) or None


def emoji_for_item(name, profile=None) -> Optional[str]:
    """``"<:item_twisted_bow:123>"`` for an item name, or None."""
    return _lookup("item", item_key(name), profile)


def emoji_for_npc(name, profile=None) -> Optional[str]:
    """``"<:npc_zulrah:123>"`` for an NPC name, or None."""
    return _lookup("npc", npc_key(name), profile)


def emoji_for_item_id(item_id, profile=None) -> Optional[str]:
    """As :func:`emoji_for_item` but from the id a ``drops`` row carries."""
    entry = _index()["item"]["by_id"].get(_int(item_id))
    return _lookup("item", entry["key"], profile) if entry else None


def emoji_for_npc_id(npc_id, profile=None) -> Optional[str]:
    """As :func:`emoji_for_npc` but from an ``npc_list`` id."""
    entry = _index()["npc"]["by_id"].get(_int(npc_id))
    return _lookup("npc", entry["key"], profile) if entry else None


def prefix_item(name, profile=None) -> str:
    """``"<:item_twisted_bow:123> Twisted bow"``, or just the name.

    The common call site: a glyph in front of a label, degrading to the bare
    label when the item is outside the set. Returns the name unchanged rather
    than a leading space, so lines stay aligned either way.
    """
    glyph = emoji_for_item(name, profile)
    return f"{glyph} {name}" if glyph else str(name or "")


def prefix_npc(name, profile=None) -> str:
    """:func:`prefix_item` for an NPC."""
    glyph = emoji_for_npc(name, profile)
    return f"{glyph} {name}" if glyph else str(name or "")


def _int(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


# --------------------------------------------------------------------------
# introspection, for the seeder and the tests
# --------------------------------------------------------------------------

def manifest_entries() -> list:
    """Every manifest entry with its ``kind`` attached, items then NPCs."""
    manifest = load_manifest()
    return ([dict(e, kind="item") for e in manifest["items"]]
            + [dict(e, kind="npc") for e in manifest["npcs"]])


def art_path_for(entry: dict) -> Path:
    """Where the seeder reads one entry's icon from."""
    directory = ITEM_ART_DIR if entry.get("kind") == "item" else NPC_ART_DIR
    return directory / f"{entry['id']}.png"


def validate_manifest() -> list:
    """Reasons the manifest could not be seeded as written (empty when fine)."""
    problems, seen_names, seen_keys = [], {}, {}
    for entry in manifest_entries():
        label = f"{entry.get('kind')} {entry.get('name')!r}"
        name = entry.get("emoji")
        if not is_valid_emoji_name(name):
            problems.append(f"{label}: {name!r} is not a valid Discord emoji name")
        if name in seen_names:
            problems.append(f"{label}: emoji name {name!r} is also claimed by {seen_names[name]!r}")
        seen_names[name] = entry.get("name")
        key = (entry.get("kind"), entry.get("key"))
        if key in seen_keys:
            problems.append(f"{label}: key {key[1]!r} is also claimed by {seen_keys[key]!r}")
        seen_keys[key] = entry.get("name")
        if not art_path_for(entry).exists():
            problems.append(f"{label}: no art at {art_path_for(entry)}")
    return problems
