"""Item names and stack-size sprite variants, read from the game cache.

Both of the things this answers used to be answered from the ``items`` table,
and both were wrong in the same way. ``items`` is not a catalogue — it only
holds what somebody has *submitted* — so it knows nothing about an item until
it has been dropped. On personal-best loadouts that meant 89 of 95 gear ids had
no row at all, which is precisely the set that also had no icon: the items that
looked broken were the items nothing knew about.

The catalogue is generated by ``scripts/cache/extract-item-catalogue.mjs`` into
``scripts/item_catalogue.json`` and committed, the same way the collection log
structure and the CA task registry are. Regenerate it after a game update.

Two questions it settles:

**Names.** Every id the site can display resolves — measured at 100% of both
the 2,069 ids in real loadouts and the 1,716 collection log slots, against
94.8% from the cache's own name field alone and 95.7% from ``items``. The
difference is noted and placeholder items, which carry no name of their own and
point at the item they stand in for.

**Stack variants.** A stackable item is stored as its single-unit id and the
game swaps to larger pile sprites as the stack grows. The cache carries the
thresholds per item, so this replaces three hand-written copies of the coin
mapping — all of which had the thresholds wrong (10/50/100 where the game
switches at 25/100/250, so 100 coins drew the 250-pile sprite).
"""
from __future__ import annotations

import json
import os
import threading
from typing import Dict, List, Optional, Tuple

CATALOGUE_PATH = "/store/droptracker/disc/scripts/item_catalogue.json"

# name, and ascending [(threshold, variant_id)] for stackables.
_Entry = Tuple[str, List[Tuple[int, int]]]

_lock = threading.Lock()
_catalogue: Optional[Dict[int, _Entry]] = None
_loaded_mtime: Optional[float] = None


def _load() -> Dict[int, _Entry]:
    """The catalogue, reloaded when the file on disk changes.

    The mtime check means a regenerated catalogue is picked up without a service
    restart, which matters because the natural time to regenerate is right after
    a game update — when new item ids are already arriving.
    """
    global _catalogue, _loaded_mtime
    try:
        mtime = os.path.getmtime(CATALOGUE_PATH)
    except OSError:
        # No catalogue on this box: callers degrade to their own fallbacks
        # rather than failing. An empty dict is a valid answer to every query
        # here ("we do not know"), which is what those fallbacks expect.
        return {}

    with _lock:
        if _catalogue is not None and _loaded_mtime == mtime:
            return _catalogue
        try:
            with open(CATALOGUE_PATH, "r", encoding="utf-8") as fh:
                raw = json.load(fh)
            items = raw.get("items") or {}
            parsed: Dict[int, _Entry] = {}
            for key, entry in items.items():
                try:
                    item_id = int(key)
                except (TypeError, ValueError):
                    continue
                if not isinstance(entry, dict):
                    continue
                name = entry.get("n")
                if not isinstance(name, str) or not name:
                    continue
                variants: List[Tuple[int, int]] = []
                for pair in entry.get("sv") or []:
                    if (
                        isinstance(pair, list)
                        and len(pair) == 2
                        and isinstance(pair[0], int)
                        and isinstance(pair[1], int)
                        and pair[0] >= 2
                        and pair[1] > 0
                    ):
                        variants.append((pair[0], pair[1]))
                variants.sort()
                parsed[item_id] = (name, variants)
            _catalogue = parsed
            _loaded_mtime = mtime
        except Exception:
            # A corrupt or half-written file must not take the API down.
            _catalogue = _catalogue or {}
        return _catalogue


def item_name(item_id) -> Optional[str]:
    """The game's name for ``item_id``, or None if the catalogue has no entry."""
    try:
        return _load().get(int(item_id), (None, None))[0]
    except (TypeError, ValueError):
        return None


def item_names(item_ids) -> Dict[int, str]:
    """``{item_id: name}`` for the ids the catalogue knows, skipping the rest."""
    catalogue = _load()
    out: Dict[int, str] = {}
    for raw in item_ids or ():
        try:
            item_id = int(raw)
        except (TypeError, ValueError):
            continue
        entry = catalogue.get(item_id)
        if entry:
            out[item_id] = entry[0]
    return out


def stack_display_id(item_id, quantity) -> int:
    """The sprite id the game would draw for ``quantity`` of ``item_id``.

    The largest variant whose threshold the quantity reaches; the base id when
    the item is not stackable, is unknown, or the quantity is below the first
    threshold. Never raises and always returns an int, so callers can use it
    unconditionally in place of the raw id.
    """
    try:
        base = int(item_id)
        count = int(quantity)
    except (TypeError, ValueError):
        return item_id
    entry = _load().get(base)
    if not entry or not entry[1]:
        return base
    display = base
    for threshold, variant_id in entry[1]:
        if count >= threshold:
            display = variant_id
        else:
            break
    return display


def largest_stack_id(item_id) -> Optional[int]:
    """The fullest pile sprite for ``item_id``, or None if it has no variants.

    The loot boards deliberately show the fullest pile regardless of quantity
    (suggestion #44), which is a different policy from :func:`stack_display_id`
    and stays a separate function for that reason — but both read the same
    thresholds, so there is only one place that knows what a stack variant is.
    """
    try:
        entry = _load().get(int(item_id))
    except (TypeError, ValueError):
        return None
    if not entry or not entry[1]:
        return None
    return entry[1][-1][1]


def stack_variant_ids(item_ids=None) -> set:
    """Every variant id reachable from ``item_ids`` (or the whole catalogue).

    The icon sweep needs this: a stack variant is an id the site can render
    without it ever having been submitted, dropped, or worn, so nothing else
    would think to fetch its icon.
    """
    catalogue = _load()
    if item_ids is None:
        sources = catalogue.items()
    else:
        wanted = set()
        for raw in item_ids:
            try:
                wanted.add(int(raw))
            except (TypeError, ValueError):
                continue
        sources = ((i, catalogue[i]) for i in wanted if i in catalogue)
    out = set()
    for _, (_, variants) in sources:
        for _, variant_id in variants:
            out.add(variant_id)
    return out
